remote_theme: "owasp/www--site-theme@main"
plugins:
 - jekyll-include-cache-0.2.0
 - jekyll-get-json

jekyll_get_json:
  - data: owaspprojects
    json: 'https://raw.githubusercontent.com/OWASP/owasp.github.io/main/_data/projects.json'
